import { SeeAlso, StatGrid, WikiPage, WikiSectionHeading } from "@/app/components/wiki";
import CraftingGrid from "@/app/components/wiki/CraftingGrid";
import { gunAmmo, gunParts } from "../data/guns";

// Keyed by part name, not by array index: an unmapped part renders its name in the
// output slot instead of silently borrowing the neighbouring part's texture.
// "Demonwood Stock" is deliberately absent - no demonwood_stock.png exists in
// public/wiki/textures/gun-parts yet.
const partTextureIds: Record<string,string> = {"Smoothbore Barrel (Long)":"smoothbore_barrel_long","Rifled Barrel (Long)":"rifled_barrel_long","Smoothbore Barrel (Short)":"smoothbore_barrel_short","Rifled Barrel (Short)":"rifled_barrel_short","Spread Barrel":"spread_barrel","Launcher Barrel":"launcher_barrel","Muzzle Loader":"muzzle_loader","Breech Loader":"breech_loader","Single Shot":"single_shot","Single Shot (launcher)":"single_shot_rocket","Quad Shot":"quad_shot_rocket","Revolver":"revolver","Steamlock":"steamlock","Matchlock":"matchlock","Flintlock":"flintlock","Rocketlock":"rocketlock","Experimental Arclock":"arclock","Oak Stock":"oak_stock","Maplewood Stock":"maplewood_stock","Elderwood Stock":"elderwood_stock"};
const materialTextures: Record<string,string> = {"Iron Ingot":"/wiki/textures/vanilla/iron_ingot.png","Steel Ingot":"/wiki/textures/materials/steel_ingot.png","Abyssalite Ingot":"/wiki/textures/materials/abyssalite_ingot.png","Mythril Ingot":"/wiki/textures/materials/mythril_ingot.png","Refined Barkwood":"/wiki/textures/materials/refined_barkwood.png","Refined Maplewood":"/wiki/textures/materials/refined_maplewood.png","Refined Elderwood":"/wiki/textures/materials/refined_elderwood.png","Refined Demonwood":"/wiki/textures/materials/refined_demonwood.png","Gravel":"/wiki/textures/vanilla/gravel.png","Gunpowder":"/wiki/textures/vanilla/gunpowder.png","Bronze Ingot":"/wiki/textures/materials/bronze_ingot.png"};
function ingredients(text:string){return text.split(" + ").map(value=>{const match=value.match(/^(\d+) (.+)$/);return {qty:Number(match?.[1]??1),name:match?.[2]??value};});}
function RecipeBox({title,station,time,requirement,output,outputQty=1,ingredientsText}:{title:string;station:string;time?:number;requirement?:string;output?:string;outputQty?:number;ingredientsText:string}) {
  const recipeIngredients = ingredients(ingredientsText).map(item => ({name:item.name,qty:item.qty,texture:materialTextures[item.name]}));
  return <CraftingGrid recipe={{key:`${station}-${title}`,title,station,time,requirement,ingredients:recipeIngredients,output:{name:title,qty:outputQty,texture:output}}}/>;
}
export default function GunsPage(){return <WikiPage title="Guns & Gunsmithing" intro="Musketeers assemble rifles, pistols, shotguns and launchers from a barrel, loader, chamber, action and, where required, a stock." width="lg">
<WikiSectionHeading id="build">Build and fire a gun</WikiSectionHeading><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm text-[var(--tfmc-mist)]"><li>Craft the Gunsmithing Station in a vanilla table: Copper–Iron–Copper on top, then Oak Planks–empty–Oak Planks for both lower rows.</li><li>As a Musketeer, right-click the placed station without sneaking and choose Rifle, Pistol, Shotgun or Launcher.</li><li>Fill slots 10–14: barrel, loader, chamber, action and stock. Pistols and launchers omit the stock. Click output slot 16.</li><li>Hold the gun in your main hand with matching ammunition in inventory. Right-click to reload, stand still until complete, then right-click once per shot.</li></ol>
<StatGrid className="mt-4" stats={[{label:"Gun types",value:"4"},{label:"Part definitions",value:"21",note:"6 barrels · 2 loaders · 4 chambers · 5 actions · 4 stocks"},{label:"Skins",value:"9",note:"chosen automatically from parts"},{label:"Ammo types",value:"6"}]}/>
<WikiSectionHeading id="parts">All gun parts</WikiSectionHeading><div className="mt-4 grid gap-4 xl:grid-cols-2">{gunParts.map(part=><RecipeBox key={`${part.kind}-${part.part}`} title={part.part} station="Gunsmithing Station" requirement={`Musketeer + ${part.rank[0].toUpperCase()+part.rank.slice(1)} Smith`} ingredientsText={part.cost} output={partTextureIds[part.part]?`/wiki/textures/gun-parts/${partTextureIds[part.part]}.png`:undefined}/>)}</div>
<WikiSectionHeading id="ammo">Ammunition</WikiSectionHeading><div className="mt-4 grid gap-4 xl:grid-cols-2">{gunAmmo.map(ammo=><RecipeBox key={ammo.ammo} title={ammo.ammo} outputQty={ammo.output} station="Alchemy Station" time={5} ingredientsText={ammo.ingredients} output={`/wiki/textures/ammunition/${ammo.ammo.toLowerCase()}.png`}/>)}</div>
<SeeAlso hrefs={["/wiki/classes","/wiki/advanced-crafting"]}/>
</WikiPage>}
