version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src/output:/app/src/output
      - ./backend/src/input:/app/src/input
      - ./backend/src/defines:/app/src/defines
    security_opt:
      - no-new-privileges:true
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    security_opt:
      - no-new-privileges:true
    restart: always